### ISSUE TITLE
Avoid CLJ-1121

### ISSUE THREAD

**Issue by greghendershott** [lexi-lambda/threading#4]
[Split out as requested from #1]

This is discussed in [rackjure issue 28](https://github.com/greghendershott/rackjure/issues/28).

http://dev.clojure.org/jira/browse/CLJ-1121

**Comment by lexi-lambda** [comment]
I don't understand this issue. The one real problem discussed in the JIRA ticket is an infinite loop, which this package does not exhibit.

The ticket mentions how the step-by-step expansion behavior of the threading macros can cause problems with "unusual macros". As far as I'm concerned, these "unusual macros" sound like _broken_ macros. Racket does provide `expand-once`, which could theoretically be used to create the same problem, but `expand-once` is rarely used in Racket because it only works at the top level. We both know that the top level is hopeless.

Macros should not depend on their "arguments" being expanded. If they do, they _must_ properly call `local-expand` to ensure that the values are what is required.

I think I understand that this could theoretically cause problems when trying to be cute and use the threading macros as shorthand for nesting of actual syntactic forms, but this seems pretty contrived and generally unhelpful, so unless a real use case is presented, I'm reluctant to consider implementing this change.

**Comment by greghendershott** [comment]
Honestly, I don't understand either. Not now. Apparently I believed that I understood, back when the issue was raised nearly 2 years ago. But there wasn't a compelling demonstration example in the JIRA issue or the rackjure issue. And I have spent some real time trying to refresh my brain on this, yesterday and today (not just copypasta-ing the issue here). Despite that, I still can't recall more that would convince either of us.

Maybe this should be closed.

**Comment by lexi-lambda** [comment]
I think I'll close it for the time being. Feel free to update me if you happen to remember why this is necessary, or if it ever comes up as a problem in real code.
